export const MENU_IMAGE = "MENU_IMAGE"
 export const API_ERROR = "SETTINGS_API_ERROR"

// export const LOGOUT_USER = "LOGOUT_USER"
// export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"


// export const SOCIAL_LOGIN = "SOCIAL_LOGIN"
// export const RECOVER_PASSWORD = "RECOVER_PASSWORD"
// export const CHANGE_NEW_PASSWORD = "CHANGE_NEW_PASSWORD"
// export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"